name: CI/CD # pipeline's name that will appear in Github Actions

on: # events that trigger our pipeline: push on any branch and release creation
  push:
  release:
    types: [created]

jobs: # jobs. We will have two jobs (test and publish) with multiple steps.
  test:
    # Our test job will run on ubuntu.
    # We define matrix strategy for python-version so that 
    # our tests are run on multiple python versions:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: [3.10]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image # install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.4
      - name: Install dependencies # install all dependencies
        run: poetry install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: test with coverage
        run:  make test-cov
